import { lib, game, ui, get, ai, _status } from "../../../../noname.js";

export const audioText = {
    //阵亡语音文本
    "#hutaoA:die": "到我了吗…",
    "#zhongliA:die": "磐石…也会归于尘土…",
    "#ganyuA:die": "「契约」…尚未完成…",
    "#keqingA:die": "太不甘心了…",
    "#qiqiA:die": "还会…被封印吗…",
    "#shenlilinghuaA:die": "让家族…蒙羞了…",
    "#shenlilingrenA:die": "世事无常…",
    "#leidianjiangjunA:die": "雷鸣…将歇…",
    "#xiaoA:die": "这是…报应吗…",
    "#xingqiuA:die": "承蒙…赐教…",
    "#xianglingA:die": "搞砸了呢…",
    "#yunjinA:die": "曲终…人散…",
    "#ningguangA:die": "这就是，「天权」的终焉？",
    "#shanhugongxinhaiA:die": "计策…出问题了吗？",
    "#bachongshenziA:die": "止步于此，何谈永恒…",
    "#fengyuanwanyeA:die": "下次…绝不会再…",
    "#wendiA:die": "啊呀，弦断了…",
    "#anboA:die": "训练…还不够…",
    "#youlaA:die": "罪人的结局吗…",
    "#banniteA:die": "没能突破…厄运的封锁…",
    "#shatangA:die": "研究…又失败了…",
    "#naxidaA:die": "我…不明白…",
    //技能语音文本
    "#ext:原梗Enhanced/audio/skill/ranhuaA1": "你很有眼光嘛！",
    "#ext:原梗Enhanced/audio/skill/ranhuaA2": "哦？该我出马了？",
    "#ext:原梗Enhanced/audio/skill/xuehuoA1": "一波送走，全送走。",
    "#ext:原梗Enhanced/audio/skill/xuehuoA2": "嗯~甚好甚好！",
    "#ext:原梗Enhanced/audio/skill/dieyinA1": "吃饱喝饱，一路走好！",
    "#ext:原梗Enhanced/audio/skill/dieyinA2": "蝶火燎原！",
    "#ext:原梗Enhanced/audio/skill/wangshengA1": "再会啦！",
    "#ext:原梗Enhanced/audio/skill/wangshengA2": "顺风顺水~",
    "#ext:原梗Enhanced/audio/skill/yuzhangA1": "安如磐石",
    "#ext:原梗Enhanced/audio/skill/yuzhangA2": "固若金汤",
    "#ext:原梗Enhanced/audio/skill/fengshenA1": "天动万象",
    "#ext:原梗Enhanced/audio/skill/fengshenA2": "此乃天道",
    "#ext:原梗Enhanced/audio/skill/bingwuA1": "起舞吧。",
    "#ext:原梗Enhanced/audio/skill/bingwuA2": "失礼了。",
    "#ext:原梗Enhanced/audio/skill/shuangmieA1": "樱吹雪。",
    "#ext:原梗Enhanced/audio/skill/shuangmieA2": "神里流…霜灭！",
    "#ext:原梗Enhanced/audio/skill/xianbuA1": "不容小觑呢。",
    "#ext:原梗Enhanced/audio/skill/xianbuA2": "久违的对手…",
    "#ext:原梗Enhanced/audio/skill/huolinA1": "「饮必甘露，食必嘉禾。」",
    "#ext:原梗Enhanced/audio/skill/huolinA2": "力量？…真是久违了。",
    "#ext:原梗Enhanced/audio/skill/shuanghuaA1": "如琉璃般飘落。",
    "#ext:原梗Enhanced/audio/skill/shuanghuaA2": "为了岩王帝君！",
    "#ext:原梗Enhanced/audio/skill/qiyueA1": "谨遵你我「契约」。",
    "#ext:原梗Enhanced/audio/skill/qiyueA2": "需要…补充能量。",
    "#ext:原梗Enhanced/audio/skill/xuanjiA1": "雕虫小技。",
    "#ext:原梗Enhanced/audio/skill/xuanjiA2": "抓紧时间吧。",
    "#ext:原梗Enhanced/audio/skill/yugeA1": "向我臣服吧。",
    "#ext:原梗Enhanced/audio/skill/yugeA2": "你的性命，我收下了。",
    "#ext:原梗Enhanced/audio/skill/caiyuanA1": "呵，劝你放弃。",
    "#ext:原梗Enhanced/audio/skill/caiyuanA2": "别白费功夫。",
};

